### PR TITLE
docs: add blog.trueberryless.org showcase

### PR DESCRIPTION
**Pull request by trueberryless**
**Describe the pull request**

Add a new entry to the showcase page for my website: blog.trueberryless.org

**Why**

I'd love to contribute, I'd love to be part of it, I love your blog extension!

### CODE REVIEW

**Comment by trueberryless** [comment]
this PR unintentionally includes #75 

what the best way to fix this?

**Comment by trueberryless** [comment]
I removed last commit of main (reset hard) and force pushed... I think it's okay (LGTM)

**Review by HiDeoo — CHANGES_REQUESTED** [review]
Thanks for the great addition :raised_hands:

For consistency with all the other showcase images, would you mind updating the image to 800x450, e.g. like this one:

blog trueberryless org

**Comment by trueberryless** [comment]
Going to do that ASAP

**Comment by trueberryless** [comment]
I forgot it ASAP xD

**Comment by HiDeoo** [comment]
> I forgot it ASAP xD

No problem 😄 Do you mind fixing the remaining conflict and we should be able to merge this new addition to the showcase 🎉

**Comment by trueberryless** [comment]
no problemo, just fixed it i think 😊

**Review by HiDeoo — APPROVED** [review]
Thanks for the new addition to the showcase 🙌

**Pull request merged**
